"""
This file contains Credentials Data
"""


def dbcred():
    data = {
        "DB_host": "34.70.96.52",
        "DB_user": "order",
        "DB_password": "acceptance",
    }
    return data


def email_cred():
    data = {

            "bangrealty@bpoacceptor.com" : "tvkutrlgskrsijuw",
            "notificationalert@bpoacceptor.com" : "opmwzicfqpybbypw",
            "keystoneholding@bpoacceptor.com" : "nlpefhinjdspzaqh",
            "notifications@bpoacceptor.com" : "srdsmjfvelbqjqsp", 
            "info@bpoacceptor.com" : "uaiqygqhqhustvlb",

            "fromaddresspwd": "Ecesis@2024",
            "notifier_email":"notifications@bpoacceptor.com",
            "notifier_password":"Ecesis@2024",
            "exception_email":"exceptionmailsend@gmail.com",
            "exception_password":"gwgckyxcikquyeat",
            "login_error_email":"loginerrornotifier@gmail.com",
            "login_error_password":"eqkmgbkfbopdkfpw",
            "internal_notifier_email":"notificationsecesis@gmail.com",
            "internal_notifier_password":"plfdctgjjxdptwzn",
            "internal_email_notification":"teamsoftware@ecesistech.com",
            "xome_email_address":"martinsinglesource@gmail.com",
            "xome_email_password":"ofjpwbcznbwtwvmd",
            "amo_email_address":"rrrfrankacc@gmail.com",
            "amo_email_password":"stzvhzqkawsplmob",
            "ca_email_address":"sharadaswbc@gmail.com",
            "ca_email_password":"ffhczdrqaszvnwbi",
            "proteck_email_address":"proteckecesis@gmail.com",
            "proteck_email_password":"pxvqouppccyxkcpt",
            "emerge_email_address":"emergeautoacceptance@gmail.com",
            "emerge_email_password":"gydsgztnuppmanau",
            "clearcapital_email_address":"ocwenedward@gmail.com",
            "clearcapital_email_password":"cpzqciikxznvdofi",
            "rrr1_email_address":"rrrecesis@gmail.com",
            "rrr1_email_password":"yujnpdghjdvnztro",
            "rrr2_email_address":"bangproteck@gmail.com",
            "rrr2_email_password":"ykbplcmdbywvluvc",
            "rrr3_email_address":"rrrhollyacc@gmail.com",
            "rrr3_email_password":"kqzvrhrowntmehfr",
            "rrr4_email_address":"ecesisrrr@gmail.com",
            "rrr4_email_password":"rpjswmlipxpgbaxk",
            "rrr5_email_address":"rrrshawnacc@gmail.com",
            "rrr5_email_password":"woxcsukpigavohux",
            "rrr6_email_address":"bronzevillebpos@gmail.com",
            "rrr6_email_password":"chudslfuwdlxyvaa",
            "rrr7_email_address":"Abradfordre1@gmail.com",
            "rrr7_email_password":"muvtyhowvibipkfu",
            "rrr8_email_address":"ali.g.realtyshow@gmail.com",
            "rrr8_email_password":"ubmljkhkfsotzmfu",
            "rrr9_email_address":"andypunia2000@gmail.com",
            "rrr9_email_password":"lzexafqmmvwcetye",
            "rrr10_email_address":"summerour1963@gmail.com",
            "rrr10_email_password":"ysugsbtaheubmrdc",
            "rrr11_email_address":"realestatebossdavid@gmail.com",
            "rrr11_email_password":"nwulpmhzaknzoree",
            "rrr12_email_address":"buyandrentwithbrent@gmail.com",
            "rrr12_email_password":"jctrcwtaybxyqkkw",
            "rrr13_email_address":"betondeb@gmail.com",
            "rrr13_email_password":"oxieiboxmehfxiyv",
            "rrr14_email_address":"dominickcolavita@gmail.com",
            "rrr14_email_password":"fmzdffbbjfotjekx",
            "rrr15_email_address":"geoffre858@gmail.com",
            "rrr15_email_password":"sdivwieecpaipcow",
            "rrr16_email_address":"eyoungrealestate1@gmail.com",
            "rrr16_email_password":"scizxvefhtlpztvp",
            "rrr17_email_address":"indianajohnson79@gmail.com",
            "rrr17_email_password":"kcylpoguckldsruz",
            "rrr18_email_address":"blackpagebpos@gmail.com",
            "rrr18_email_password":"tpojslwjhpujpbva",
            "rrr19_email_address":"cemani.latrice@gmail.com",
            "rrr19_email_password":"lmvnveglcskmgdzm",
            "rrr20_email_address":"realveronicadiaz@gmail.com",
            "rrr20_email_password":"rnralkxxiipixscm",
            "rrr21_email_address":"myoungrealestate1@gmail.com",
            "rrr21_email_password":"joduqkihqwteopae",
            "rrr22_email_address":"moresigningsre@gmail.com",
            "rrr22_email_password":"unwmntfzxicbubse",
            "rrr23_email_address":"markdarebpos@gmail.com",
            "rrr23_email_password":"ovtvgsgxcfyjwvpi",
            "rrr24_email_address":"pierre.realty1@gmail.com",
            "rrr24_email_password":"cpyeyzxmgtfgtagm",
            "rrr25_email_address":"patrick.at.world@gmail.com",
            "rrr25_email_password":"jbcxtugcblslfeab",
            "rrr26_email_address":"texasallyrichard@gmail.com",
            "rrr26_email_password":"ioznjmjyrxmryjpr",
            "rrr27_email_address":"inspiredsandy@gmail.com",
            "rrr27_email_password":"wooubylsajoouhot",
            "rrr28_email_address":"calebfreesebpo@gmail.com",
            "rrr28_email_password":"sglwdvzktqjkampq",
            "rrr29_email_address":"connorfreesebpo@gmail.com",
            "rrr29_email_password":"zxlyhntctbwxmbmb",
            "rrr30_email_address":"ryanwbpos@gmail.com",
            "rrr30_email_password":"faytpyobhnixvdoc",
            "rrr31_email_address":"wegnersells@gmail.com",
            "rrr31_email_password":"sumyvfkhaqmjofix",
            "rrr32_email_address":"jodipage3@gmail.com",
            "rrr32_email_password":"tpicxepknufscsqz",
            "rrr33_email_address":"silvercirclebpos@gmail.com",
            "rrr33_email_password":"kfcvzslxxlqqamfu",
            "singlesource_email_address":"ocwenecesis@gmail.com",
            "singlesource_email_password":"ydfxojutcsijrqnn",
            "avm_email_address":"avmecesis@gmail.com",
            "avm_email_password":"azefbljqdhodvxzb",
            "estreet_email_address":"sssharynacc@gmail.com",
            "estreet_email_password":"aspcawrgbobcsotm",
            "soldifi_email_address":"ecesism2m@gmail.com",
            "soldifi_email_password":"gwaemyoofqtwiyjh",
            "summitvaluation_email_address":"summitvalaccept@gmail.com",
            "summitvaluation_email_password":"didpxmiosehvdzkz",
            "swbc_email_address":"rrrlynneacc@gmail.com",
            "swbc_email_password":"azuhezxvwcyruqeb",
            "swbc_inter":"swbcinter@gmail.com",
            "exception_ecesis":"exceptionecesis@gmail.com",
            "capacity_mail":"bpo2@bangrealty.com",
            "capacity_mail_sent":"max@bangrealty.com",
            "ignored_mail":"notificationacceptance@gmail.com",
            "ignored_psswd":"dfmcswifawwkhyni",
            "ignored_bang_mail": "notificationalert@bpoacceptor.com",
            "ignored_bang_mail_password": "opmwzicfqpybbypw"
            }
    return data


